version : '3.1'
services:
        mongo: 
                image: mongo
                container_name: 'mongo_armario'
                restart: always
                environment:
                        - MONGO_INITDB_DATABASE=armario
                        - MONGO_INITDB_ROOT_USERNAME=root
                        - MONGO_INITDB_ROOT_PASSWORD=123456
                volumes:
                        - ./.mongo/entry-point.js:/docker-entrypoint-initdb.d/init-mongo.js 
                        - ./.mongo/db:/data/db
                ports:
                        - '27017:27017'
                networks: 
                        - armario             
networks: 
        armario:
                driver: 'bridge'


